Add support for the theme collection
hassio-addons/addon-node-red pull request #970
Opened 2021-04-09 12:14 UTC by bonanitech

# Proposed Changes

This adds the collection of themes created by the @node-red-contrib-themes team, giving the users the option to choose which theme to use in their systems.

## Related Issues

N/A

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

2021-04-10 10:02 UTC, frenck requested changes

2021-04-10 10:02 UTC, frenck commented on node-red/config.json
>      "dark_mode": false,
Lets remove `dark_mode` from the default configuration (but keep it in the schema). That way, it won't show up on new installations.

2021-04-10 10:02 UTC, frenck commented on node-red/config.json
> +    "theme": "",
Default should be null?

2021-04-10 10:02 UTC, frenck commented on node-red/config.json
>      "dark_mode": "bool",
```suggestion
    "dark_mode": "bool?",
```

2021-04-10 10:02 UTC, frenck commented on node-red/rootfs/etc/node-red/config.js
> +// Set theme
The old code above can set a theme the same way, right?

- If the old dark_mode option is found, the `theme: "midnight-red"`?
- Let's print a warning if we detect the old option is still used (this warning should be printed in `rootfs/etc/cont-init.d/node-red.sh`)

2021-04-11 11:09 UTC, bonanitech commented on node-red/rootfs/etc/node-red/config.js
> +// Set theme
> * Let's print a warning if we detect the old option is still used (this warning should be printed in `rootfs/etc/cont-init.d/node-red.sh`)

"The dark_mode option has been deprecated and will be removed in a future version. Please use the theme option instead."

Something like that?

2021-04-11 11:29 UTC, bonanitech commented on node-red/DOCS.md
> +### Option: `dark_mode` (DEPRECATED)
Should I also remove/change the note on line 136?

2021-04-11 12:01 UTC, frenck commented on node-red/DOCS.md
> +### Option: `dark_mode` (DEPRECATED)
Yes, let's make it as if it was never there 👍

2021-04-11 12:01 UTC, frenck commented on node-red/rootfs/etc/node-red/config.js
> +// Set theme
Yeah, that will do 👍

2021-04-11 12:25 UTC, bonanitech commented
dark_move? 🤦🏼 😂

2021-04-11 18:10 UTC, sinclairpaul commented
We could migrate the dark_mode key automatically with bashio couldn't we?

2021-04-15 21:56 UTC, frenck commented on node-red/config.json
> +    "theme": "match((dark|midnight-red|oled|solarized-dark|solarized-light)(-scroll)?|(default))",
We should make this a `list()` type, that way, the UI will show a dropdown (when possible).

2021-04-15 21:59 UTC, frenck commented
> We could migrate the dark_mode key automatically with bashio couldn't we?

Maybe we could, but considering the quite interesting config, this add-on can have (weird passwords, secrets references, lists of additional stuff), let's avoid breaking things. A warning is fine, we can leave this option around for quite some time as well (as in, 🤷)

2021-04-15 23:48 UTC, bonanitech commented on node-red/config.json
> +    "theme": "match((dark|midnight-red|oled|solarized-dark|solarized-light)(-scroll)?|(default))",
Done!

2021-04-20 11:01 UTC, frenck approved these changes
Some small tweaks, to make it non-breaking if `theme` is not in the configuration.

2021-04-20 11:01 UTC, frenck commented on node-red/config.json
> +    "theme": "list(default|dark|midnight-red|oled|solarized-dark|solarized-light)",
```suggestion
    "theme": "list(default|dark|midnight-red|oled|solarized-dark|solarized-light)?",
```

2021-04-20 11:01 UTC, frenck commented on node-red/rootfs/etc/node-red/config.js
> +else if (options.theme) {
```suggestion
else if ("theme" in options) {
```

2021-04-20 11:05 UTC, frenck commented
Rebased onto the latest upstream branch, to ensure the new build flow triggers / is used.

2021-04-20 11:55 UTC, merged

2021-04-21 21:13 UTC, Zorgino commented on node-red/rootfs/etc/node-red/config.js
> +    theme: "midnight-red",
editorTheme object also contains other vital settings, like `projects`.
@frenck, it needs to be reverted ASAP.

it has already broken my setup, glad, I was able to downgrade.